version: '3.1'

services:
  php:
    build: ./image/php/
    ports:
      - ${PHP_PORT}:9000
    volumes:
      - ./commissionator/:/var/www/html
  nginx:
    image: nginx:latest
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
